// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiSiJ9_MKfbINv-T0uzZSH174fqbhVhnQ',
    appId: '1:981122937319:web:eafe9e3cdb311ca1878d42',
    messagingSenderId: '981122937319',
    projectId: 'first-aid-app-v1',
    authDomain: 'first-aid-app-v1.firebaseapp.com',
    storageBucket: 'first-aid-app-v1.firebasestorage.app',
    measurementId: 'G-TJX04F6PWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:981122937319:android:5b35c16bb1e7fe31878d42',
    messagingSenderId: '981122937319',
    projectId: 'first-aid-app-v1',
    storageBucket: 'first-aid-app-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKL2qcpgr2XfkDs91qEpgLTC15scacAQU',
    appId: '1:981122937319:ios:b36b7f0840479023878d42',
    messagingSenderId: '981122937319',
    projectId: 'first-aid-app-v1',
    storageBucket: 'first-aid-app-v1.firebasestorage.app',
    iosBundleId: 'com.example.firstAidApp',
  );
}
